### ISSUE TITLE
Setting up Jhipster-ide for Azure Pipelines

### ISSUE THREAD

**Issue by Shaolans** [jhipster/jhipster-ide#275] opened 2019-05-23 15:03 UTC
**Overview of the feature request**

Since Travis future is now uncertain, we should progressively migrate our CI to Azure Pipelines like we did for the generator or prettier-java.

**Motivation for or Use Case**

Travis is not doing well.
Azure Pipelines can have up to 10 parallel jobs (5 for Travis)

**Comment by pascalgrimaud** [comment] 2019-05-24 19:15
@colameo : it should be good now - see https://dev.azure.com/jhipster/jhipster-ide/_build?definitionId=14
Don't hesitate to ping me if the Azure build is not triggered for pull request or merge into master.
I delete the existing webhooks, it's probably because you tried to configure the build

Then the Azure build failed for some reason.
I'll let you investigate, tell me if you are stuck

**Comment by colameo** [comment] 2019-06-17 08:02
No it's not good - i've just commented out the build statements in the azure-pipelines yaml file.
Before the build runs we need to make sure that no .m2 repository or workspace with artefacts from an old build is visible to the reactor. However, I can manage it by my own if you give me the rights to do so...

**Comment by colameo** [comment] 2019-06-17 08:09
...however, the travis build works as expected and I can live with that for the moment. So, it's not urgent at all for me

**Comment by pascalgrimaud** [comment] 2019-06-17 08:42
For your information. I just cloned this project, and tried to reproduce the issue. I got the same result as Azure.
Here my logs:

```
Download https://jcenter.bintray.com/com/google/guava/guava/21.0/guava-21.0.jar
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.core.runtime/3.15.200/org.eclipse.core.runtime-3.15.200.jar
0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - [XtextLinkingDiagnostic: null:10 Couldn't resolve reference to JvmType 'postprocessor.JdlLanguageGenerator'., XtextLinkingDiagnostic: null:11 Couldn't resolve reference to JvmIdentifiableElement 'configuration'., XtextLinkingDiagnostic: null:12 Couldn't resolve reference to JvmIdentifiableElement 'project'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'code'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'encoding'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'language'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:10 Couldn't resolve reference to JvmType 'postprocessor.JdlLanguageGenerator'., XtextLinkingDiagnostic: null:11 Couldn't resolve reference to JvmIdentifiableElement 'configuration'., XtextLinkingDiagnostic: null:12 Couldn't resolve reference to JvmIdentifiableElement 'project'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'code'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'encoding'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'language'.]
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:88)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
:jdl:io.github.jhipster.jdl:generateXtextLanguage FAILED
:installServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':io.github.jhipster.jdl:generateXtextLanguage'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 8.449 secs
```

Here the Azure logs :

```
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.osgi/3.13.300/org.eclipse.osgi-3.13.300.jar
Download https://jcenter.bintray.com/org/eclipse/emf/org.eclipse.emf.mwe2.runtime/2.9.1.201705291010/org.eclipse.emf.mwe2.runtime-2.9.1.201705291010.jar
Download https://jcenter.bintray.com/org/sonatype/sisu/inject/cglib/2.2.1-v20090111/cglib-2.2.1-v20090111.jar
Download https://jcenter.bintray.com/com/google/guava/guava/21.0/guava-21.0.jar
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.core.runtime/3.15.200/org.eclipse.core.runtime-3.15.200.jar
0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - [XtextLinkingDiagnostic: null:10 Couldn't resolve reference to JvmType 'postprocessor.JdlLanguageGenerator'., XtextLinkingDiagnostic: null:11 Couldn't resolve reference to JvmIdentifiableElement 'configuration'., XtextLinkingDiagnostic: null:12 Couldn't resolve reference to JvmIdentifiableElement 'project'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'code'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'encoding'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'language'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:10 Couldn't resolve reference to JvmType 'postprocessor.JdlLanguageGenerator'., XtextLinkingDiagnostic: null:11 Couldn't resolve reference to JvmIdentifiableElement 'configuration'., XtextLinkingDiagnostic: null:12 Couldn't resolve reference to JvmIdentifiableElement 'project'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'code'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'encoding'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'language'.]
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:88)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
:jdl:io.github.jhipster.jdl:generateXtextLanguage FAILED
:installServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':io.github.jhipster.jdl:generateXtextLanguage'.
> Process 'command '/usr/lib/jvm/zulu-8-azure-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 31.47 secs
##[error]Bash exited with code '1'.
##[section]Finishing: GRADLE: installServer
```

**Comment by pascalgrimaud** [comment] 2019-06-17 08:45
@colameo : you can look at the Travis logs. There are the same errors, but Travis considered the build to pass, instead of fail.
So for me, there is a real issue.
- Azure detected it
- Travis not

**Comment by colameo** [comment] 2019-06-17 10:41
> @colameo : you can look at the Travis logs. There are the same errors, but Travis considered the build to pass, instead of fail.
> So for me, there is a real issue.
> 
> * Azure detected it
> * Travis not

...interesting, I'll this night a look - thanks for pointing that out!

**Comment by colameo** [comment] 2019-06-17 18:29
ok, I've investigated deeper in the frameworks we use behind the scenes and it turned out that some of the dependencies are deprecated ... however, the workaround is that I need to update the underlying stuff to the newest versions. 

So, I close this issue as it has nothing to do with Azure pipelines. 

BTW, it's really strange that Travis does not discover that exception... one more reason to move completely away...

**Closed by colameo** 2019-06-17 18:29 UTC
Labels: task
