### ISSUE TITLE
[Eclipse] Shell script (yeoman jhipster + mvn)  is not called when a "Terminal" tab is already open

### ISSUE THREAD

**Issue by xdworkshop** [jhipster/jhipster-ide#148] opened 2017-08-19 16:30 UTC
Shell script (yeoman jhipster + mvn)  is not called when a "Terminal" tab is already open

**Comment by colameo** [comment] 2017-08-27 10:19
could not reproduce: 
![jhidetabissue](https://user-images.githubusercontent.com/629760/29748942-b74f6e4a-8b21-11e7-80dc-ce3047994f7b.gif) 
please provide more information about your eclipse setup (version, which basis distribution you used etc.) or just try with a fresh eclipse distro to reinstall JHipster IDE.
...let me know I this issue persists.

**Comment by colameo** [comment] 2017-08-27 10:21
I close it, please reopen if you can reproduce with more information. thanks!

**Closed by colameo** 2017-08-27 10:21 UTC
Labels: enhancement
